# Generated by Django 5.0.6 on 2024-06-23 06:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_alter_funding_options'),
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='source',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='end_date',
        ),
        migrations.AddField(
            model_name='funding',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
