# Generated by Django 5.0.6 on 2024-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0003_rename_source_funding_name_remove_funding_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
