# Generated by Django 5.0.6 on 2024-06-23 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0004_alter_funding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
