# Generated by Django 5.0.6 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0005_alter_funding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
