# Generated by Django 5.0.6 on 2024-06-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
    ]
