# Generated by Django 5.0.6 on 2024-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Vidéo')], default='text', max_length=10),
        ),
    ]
