# Generated by Django 5.0.6 on 2024-06-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/'),
        ),
    ]
