# Generated by Django 5.0.6 on 2024-06-09 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('rich_text', 'Rich Text')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('media_files', models.ManyToManyField(blank=True, related_name='publication_versions', to='publications.media')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('web', 'Web'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_publication', to='publications.publicationversion')),
                ('initial_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_publication', to='publications.publicationversion')),
            ],
        ),
    ]
