# Generated by Django 5.0.6 on 2024-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationversion',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='publication_versions', to='publications.media'),
        ),
    ]
