# Generated by Django 5.0.6 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publicationversion_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationversion',
            name='version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
