# Generated by Django 5.0.6 on 2024-06-01 18:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('rich_text', 'Rich Text')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='PublicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField(default=datetime.datetime.today)),
                ('journal', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_files', models.ManyToManyField(blank=True, related_name='publication_versions', to='publications.media')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='publications.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_publication', to='publications.publicationversion'),
        ),
        migrations.AddField(
            model_name='publication',
            name='initial_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_publication', to='publications.publicationversion'),
        ),
    ]
