# Generated by Django 5.0.6 on 2024-06-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_alter_publicationversion_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationversion',
            name='content',
        ),
    ]
