# Generated by Django 5.0.6 on 2024-06-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_publicationversion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationversion',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='publications.publication'),
        ),
    ]
