# Generated by Django 5.0.6 on 2024-06-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_publicationversion_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationversion',
            name='authors',
            field=models.CharField(max_length=200),
        ),
    ]
